// Generated by nuxi
/// <reference types="@unocss/nuxt" />
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="../../../apps/h5/.nuxt/imports" />
/// <reference types="../../../apps/h5/.nuxt/nuxt" />
