export interface userSetting {
  with_draw?: number;
}

// 老publicInfo 中 系统开关配置
// switch: {
//   is_return_open: '0',
//   saas_otc_flow_config: '0',
//   index_international_open: '0',
//   nameVerifiedType: '',
//   incrementConfigStatus: 0,
//   newcoinOpen: '1',
//   lever_open: '1',
//   config_footer_open: '1',
//   fiat_open: '0',
//   is_inner_transfer_open: '0',
//   openLoginVerificationMode: '1',
//   symbol_profile: '1',
//   indep_co_switch: '0',
//   coin_tag_open: '0',
//   is_open_upload_img: '0',
//   index_kline_switch: '0',
//   register_cms_style: '0',
//   user_role_level_open: '0',
//   interfaceSwitch: '0',
//   fiat_trade_open: '0',
//   optional_symbol_server_open: '1',
//   is_deposit_open: '0',
//   config_header_open: '1',
//   etfNavigationSwitch: '0',
//   lock_position_v2_status: '0',
//   ui_change_open: '1',
//   coins_krw_open: '0',
//   login_regist_type: '1',
//   is_invitationCode_required: '0',
//   is_enforce_google_auth: '1',
//   regist_must_check_open: '1',
//   index_temp_type: '0',
//   wind_control_switch: '0',
//   yskyc_is_open: '0',
//   client_img_upload_open: '0',
//   is_invite_open: '0',
//   agentUserOpen: '1',
//   verificationType: '1',
//   index_layer_open: '0',
//   business_id: '',
//   trade_depth_is_flash: '0',
//   open_txid_addr: '0',
// },
