const Languages = {
  ar_sa: 'ar',
  zh_CN: 'zh',
  cs_CZ: 'cs',
  da_DK: 'da_DK',
  ca_ES: 'ca_ES',
  nl_NL: 'nl_NL',
  en_US: 'en',
  et_EE: 'et_EE',
  fr_FR: 'fr',
  de_DE: 'de',
  el_CY: 'el',
  he_IL: 'he_IL',
  hu_HU: 'hu_HU',
  id_ID: 'id',
  it_IT: 'it',
  ja_JA: 'ja',
  ko_KR: 'ko',
  fa_AF: 'fa',
  pl_PL: 'pl',
  pt_PT: 'pt',
  ro_RO: 'ro',
  ru_RU: 'ru',
  sk_SK: 'sk_SK',
  es_ES: 'es',
  sv: 'sv',
  th_TH: 'th',
  tr_TR: 'tr',
  vi_VN: 'vi',
  nb_NO: 'no',
  ms_BN: 'ms_MY',
  zh_TW: 'zh_TW'
} as const;

export { Languages };
